// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwdgzocpgunadfuyeluz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZGd6b2NwZ3VuYWRmdXllbHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTgwOTgsImV4cCI6MjA3MjMzNDA5OH0.jhXPpzri5GJFp7V1w7smmP00teqGjlwlnrplsJeVR90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});